### ISSUE TITLE
[How to] Use SteamListingService?

### ISSUE THREAD

**Issue by KingNyuels** [pvanassen/steam-api#2]
* I would like to access the methods "getAsyncNewlyListed"/"getAsyncListed" but am too dumb to understand your class "GenericHandle".

* How do I call these methods correctly? Can you give me an example =D (e.g. for getting the new listed items of 'P250%20%7C%20Sand%20Dune%20%28Battle-Scarred%29'/P250 Sand Dunes Battle Scarred)?

        Thank you
            KingNyuels

**Comment by pvanassen** [comment]
Hi, 

I think it's not your 'dumbness' here but more my lack of documentation. To use the Listed or NewlyListed method you need to create a class which implements GenericHandle<Listing>. This class will have the to implement the handle(Listing listing) method. 

This method will be called for each of the items found.

**Comment by KingNyuels** [comment]
Thank you very much sir =D!

KingNyuels

**Comment by pvanassen** [comment]
I hope this will help you, if not please reopen this topic. I will close it for now.
